// Central UI theme tokens and helpers

export const uiThemes = {
  dark: {
    name: 'Koyu',
    tokens: {
      '--bg': '#000000',
      '--text': '#ffffff',
      '--surface': '#111111',
      '--surface-2': '#1a1a1a',
      '--border': '#333333',
      '--muted': '#dddddd',
      '--primary': '#00d4ff',
      '--primary-hover': '#00a8cc',
      '--primary-contrast': '#0f0f0f',
      '--accent': '#ff6b6b',
      '--success': '#28a745',
      '--danger': '#dc3545',
      '--danger-hover': '#b62a37',
      '--danger-contrast': '#ffffff',
      '--warning': '#ffc107',
      '--link': '#00d4ff',
      '--link-hover': '#ffffff',
      '--header-bg': '#0f0f0f',
      '--focus-outline': '#ffffff',
      '--accent-gradient-start': '#667eea',
      '--accent-gradient-end': '#764ba2',
      '--accent-shadow': 'rgba(102, 126, 234, 0.3)',
      '--accent-border': '#667eea',
      '--primary-veil': 'rgba(0, 212, 255, 0.1)'
    },
  },
  light: {
    name: 'Açık',
    tokens: {
      '--bg': '#ffffff',
      '--text': '#111111',
      '--surface': '#f7f7f7',
      '--surface-2': '#eeeeee',
      '--border': '#d0d0d0',
      '--muted': '#555555',
      '--primary': '#0066cc',
      '--primary-hover': '#0055aa',
      '--primary-contrast': '#ffffff',
      '--accent': '#e85d75',
      '--success': '#2e7d32',
      '--danger': '#c62828',
      '--danger-hover': '#a31f1f',
      '--danger-contrast': '#ffffff',
      '--warning': '#b26a00',
      '--link': '#0066cc',
      '--link-hover': '#003366',
      '--header-bg': '#ffffff',
      '--focus-outline': '#003366',
      '--accent-gradient-start': '#8ec5fc',
      '--accent-gradient-end': '#e0c3fc',
      '--accent-shadow': 'rgba(142, 197, 252, 0.3)',
      '--accent-border': '#8ec5fc',
      '--primary-veil': 'rgba(0, 102, 204, 0.1)'
    },
  },
  highContrast: {
    name: 'Yüksek Kontrast',
    tokens: {
      '--bg': '#000000',
      '--text': '#ffffff',
      '--surface': '#000000',
      '--surface-2': '#000000',
      '--border': '#ffffff',
      '--muted': '#ffffff',
      '--primary': '#ffff00',
      '--primary-hover': '#ffd700',
      '--primary-contrast': '#000000',
      '--accent': '#00ffff',
      '--success': '#00ff00',
      '--danger': '#ff0033',
      '--danger-hover': '#ff3366',
      '--danger-contrast': '#000000',
      '--warning': '#ff9900',
      '--link': '#ffff00',
      '--link-hover': '#ffffff',
      '--header-bg': '#000000',
      '--focus-outline': '#ffffff',
      '--accent-gradient-start': '#ffff00',
      '--accent-gradient-end': '#00ffff',
      '--accent-shadow': 'rgba(255,255,0,0.4)',
      '--accent-border': '#ffff00',
      '--primary-veil': 'rgba(255, 255, 0, 0.2)'
    },
  },
  midnightBlue: {
    name: 'Midnight Blue',
    tokens: {
      '--bg': '#0f172a',
      '--text': '#e2e8f0',
      '--surface': '#0f172a',
      '--surface-2': '#1e293b',
      '--border': '#334155',
      '--muted': '#cbd5e1',
      '--primary': '#3b82f6',
      '--primary-hover': '#2563eb',
      '--primary-contrast': '#ffffff',
      '--accent': '#60a5fa',
      '--success': '#22c55e',
      '--danger': '#ef4444',
      '--danger-hover': '#dc2626',
      '--danger-contrast': '#ffffff',
      '--warning': '#f59e0b',
      '--link': '#60a5fa',
      '--link-hover': '#93c5fd',
      '--header-bg': '#0f172a',
      '--focus-outline': '#ffffff',
      '--accent-gradient-start': '#3b82f6',
      '--accent-gradient-end': '#60a5fa',
      '--accent-shadow': 'rgba(59, 130, 246, 0.3)',
      '--accent-border': '#3b82f6',
      '--primary-veil': 'rgba(59, 130, 246, 0.12)'
    },
  },
  charcoal: {
    name: 'Charcoal',
    tokens: {
      '--bg': '#18181b',
      '--text': '#e4e4e7',
      '--surface': '#18181b',
      '--surface-2': '#27272a',
      '--border': '#3f3f46',
      '--muted': '#a1a1aa',
      '--primary': '#8b5cf6',
      '--primary-hover': '#7c3aed',
      '--primary-contrast': '#ffffff',
      '--accent': '#a78bfa',
      '--success': '#22c55e',
      '--danger': '#ef4444',
      '--danger-hover': '#dc2626',
      '--danger-contrast': '#ffffff',
      '--warning': '#f59e0b',
      '--link': '#a78bfa',
      '--link-hover': '#c4b5fd',
      '--header-bg': '#18181b',
      '--focus-outline': '#ffffff',
      '--accent-gradient-start': '#8b5cf6',
      '--accent-gradient-end': '#a78bfa',
      '--accent-shadow': 'rgba(139, 92, 246, 0.3)',
      '--accent-border': '#8b5cf6',
      '--primary-veil': 'rgba(139, 92, 246, 0.12)'
    },
  },
  forestNight: {
    name: 'Forest Night',
    tokens: {
      '--bg': '#0f1611',
      '--text': '#dcfce7',
      '--surface': '#0f1611',
      '--surface-2': '#1a2421',
      '--border': '#243330',
      '--muted': '#bbf7d0',
      '--primary': '#10b981',
      '--primary-hover': '#059669',
      '--primary-contrast': '#ffffff',
      '--accent': '#34d399',
      '--success': '#22c55e',
      '--danger': '#ef4444',
      '--danger-hover': '#dc2626',
      '--danger-contrast': '#ffffff',
      '--warning': '#f59e0b',
      '--link': '#34d399',
      '--link-hover': '#86efac',
      '--header-bg': '#0f1611',
      '--focus-outline': '#ffffff',
      '--accent-gradient-start': '#10b981',
      '--accent-gradient-end': '#34d399',
      '--accent-shadow': 'rgba(16, 185, 129, 0.3)',
      '--accent-border': '#10b981',
      '--primary-veil': 'rgba(16, 185, 129, 0.12)'
    },
  },
  monochrome: {
    name: 'Monochrome Dark',
    tokens: {
      '--bg': '#000000',
      '--text': '#e5e5e5',
      '--surface': '#0a0a0a',
      '--surface-2': '#121212',
      '--border': '#1a1a1a',
      '--muted': '#999999',
      '--primary': '#ffffff',
      '--primary-hover': '#f5f5f5',
      '--primary-contrast': '#000000',
      '--accent': '#e5e5e5',
      '--success': '#cccccc',
      '--danger': '#e5e5e5',
      '--danger-hover': '#cccccc',
      '--danger-contrast': '#000000',
      '--warning': '#999999',
      '--link': '#e5e5e5',
      '--link-hover': '#ffffff',
      '--header-bg': '#0a0a0a',
      '--focus-outline': '#ffffff',
      '--accent-gradient-start': '#ffffff',
      '--accent-gradient-end': '#666666',
      '--accent-shadow': 'rgba(255, 255, 255, 0.08)',
      '--accent-border': '#f5f5f5',
      '--primary-veil': 'rgba(255, 255, 255, 0.08)'
    },
  },
};

export const themeNames = Object.keys(uiThemes);

export function applyThemeTokens(themeKey) {
  const theme = uiThemes[themeKey] || uiThemes.dark;
  const root = document.documentElement;
  const tokens = theme.tokens;
  for (const [varName, value] of Object.entries(tokens)) {
    root.style.setProperty(varName, value);
  }
}

